"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateNationalIdDto = exports.ApplicationStatus = exports.MaritalStatus = exports.Gender = void 0;
var class_validator_1 = require("class-validator");
var class_transformer_1 = require("class-transformer");
// Define enums locally instead of importing from Prisma
var Gender;
(function (Gender) {
    Gender["MALE"] = "MALE";
    Gender["FEMALE"] = "FEMALE";
})(Gender || (exports.Gender = Gender = {}));
var MaritalStatus;
(function (MaritalStatus) {
    MaritalStatus["NEVER_MARRIED"] = "NEVER_MARRIED";
    MaritalStatus["MARRIED"] = "MARRIED";
    MaritalStatus["DIVORCED"] = "DIVORCED";
    MaritalStatus["WIDOWED"] = "WIDOWED";
    MaritalStatus["SEPARATED"] = "SEPARATED";
    MaritalStatus["ABANDONED"] = "ABANDONED";
})(MaritalStatus || (exports.MaritalStatus = MaritalStatus = {}));
var ApplicationStatus;
(function (ApplicationStatus) {
    ApplicationStatus["PENDING"] = "PENDING";
    ApplicationStatus["VERIFIED"] = "VERIFIED";
    ApplicationStatus["APPROVED"] = "APPROVED";
    ApplicationStatus["REJECTED"] = "REJECTED";
    ApplicationStatus["COMPLETED"] = "COMPLETED";
})(ApplicationStatus || (exports.ApplicationStatus = ApplicationStatus = {}));
var CreateNationalIdDto = function () {
    var _a;
    var _firstName_decorators;
    var _firstName_initializers = [];
    var _firstName_extraInitializers = [];
    var _otherNames_decorators;
    var _otherNames_initializers = [];
    var _otherNames_extraInitializers = [];
    var _surname_decorators;
    var _surname_initializers = [];
    var _surname_extraInitializers = [];
    var _nationality_decorators;
    var _nationality_initializers = [];
    var _nationality_extraInitializers = [];
    var _secondNationality_decorators;
    var _secondNationality_initializers = [];
    var _secondNationality_extraInitializers = [];
    var _dateOfBirth_decorators;
    var _dateOfBirth_initializers = [];
    var _dateOfBirth_extraInitializers = [];
    var _gender_decorators;
    var _gender_initializers = [];
    var _gender_extraInitializers = [];
    var _districtOfBirth_decorators;
    var _districtOfBirth_initializers = [];
    var _districtOfBirth_extraInitializers = [];
    var _taOfBirth_decorators;
    var _taOfBirth_initializers = [];
    var _taOfBirth_extraInitializers = [];
    var _villageOfBirth_decorators;
    var _villageOfBirth_initializers = [];
    var _villageOfBirth_extraInitializers = [];
    var _birthCertificateNo_decorators;
    var _birthCertificateNo_initializers = [];
    var _birthCertificateNo_extraInitializers = [];
    var _maritalStatus_decorators;
    var _maritalStatus_initializers = [];
    var _maritalStatus_extraInitializers = [];
    var _eyeColor_decorators;
    var _eyeColor_initializers = [];
    var _eyeColor_extraInitializers = [];
    var _height_decorators;
    var _height_initializers = [];
    var _height_extraInitializers = [];
    var _mobilePhone_decorators;
    var _mobilePhone_initializers = [];
    var _mobilePhone_extraInitializers = [];
    var _passportNo_decorators;
    var _passportNo_initializers = [];
    var _passportNo_extraInitializers = [];
    var _disability_decorators;
    var _disability_initializers = [];
    var _disability_extraInitializers = [];
    var _residentialDistrict_decorators;
    var _residentialDistrict_initializers = [];
    var _residentialDistrict_extraInitializers = [];
    var _residentialTA_decorators;
    var _residentialTA_initializers = [];
    var _residentialTA_extraInitializers = [];
    var _residentialVillage_decorators;
    var _residentialVillage_initializers = [];
    var _residentialVillage_extraInitializers = [];
    var _permanentDistrict_decorators;
    var _permanentDistrict_initializers = [];
    var _permanentDistrict_extraInitializers = [];
    var _permanentTA_decorators;
    var _permanentTA_initializers = [];
    var _permanentTA_extraInitializers = [];
    var _permanentVillage_decorators;
    var _permanentVillage_initializers = [];
    var _permanentVillage_extraInitializers = [];
    var _motherIdNo_decorators;
    var _motherIdNo_initializers = [];
    var _motherIdNo_extraInitializers = [];
    var _motherFullName_decorators;
    var _motherFullName_initializers = [];
    var _motherFullName_extraInitializers = [];
    var _motherNationality_decorators;
    var _motherNationality_initializers = [];
    var _motherNationality_extraInitializers = [];
    var _motherDistrict_decorators;
    var _motherDistrict_initializers = [];
    var _motherDistrict_extraInitializers = [];
    var _motherTA_decorators;
    var _motherTA_initializers = [];
    var _motherTA_extraInitializers = [];
    var _motherVillage_decorators;
    var _motherVillage_initializers = [];
    var _motherVillage_extraInitializers = [];
    var _fatherIdNo_decorators;
    var _fatherIdNo_initializers = [];
    var _fatherIdNo_extraInitializers = [];
    var _fatherFullName_decorators;
    var _fatherFullName_initializers = [];
    var _fatherFullName_extraInitializers = [];
    var _fatherNationality_decorators;
    var _fatherNationality_initializers = [];
    var _fatherNationality_extraInitializers = [];
    var _fatherDistrict_decorators;
    var _fatherDistrict_initializers = [];
    var _fatherDistrict_extraInitializers = [];
    var _fatherTA_decorators;
    var _fatherTA_initializers = [];
    var _fatherTA_extraInitializers = [];
    var _fatherVillage_decorators;
    var _fatherVillage_initializers = [];
    var _fatherVillage_extraInitializers = [];
    var _firstWitnessIdNo_decorators;
    var _firstWitnessIdNo_initializers = [];
    var _firstWitnessIdNo_extraInitializers = [];
    var _secondWitnessIdNo_decorators;
    var _secondWitnessIdNo_initializers = [];
    var _secondWitnessIdNo_extraInitializers = [];
    return _a = /** @class */ (function () {
            function CreateNationalIdDto() {
                this.firstName = __runInitializers(this, _firstName_initializers, void 0);
                this.otherNames = (__runInitializers(this, _firstName_extraInitializers), __runInitializers(this, _otherNames_initializers, void 0));
                this.surname = (__runInitializers(this, _otherNames_extraInitializers), __runInitializers(this, _surname_initializers, void 0));
                this.nationality = (__runInitializers(this, _surname_extraInitializers), __runInitializers(this, _nationality_initializers, void 0));
                this.secondNationality = (__runInitializers(this, _nationality_extraInitializers), __runInitializers(this, _secondNationality_initializers, void 0));
                this.dateOfBirth = (__runInitializers(this, _secondNationality_extraInitializers), __runInitializers(this, _dateOfBirth_initializers, void 0));
                this.gender = (__runInitializers(this, _dateOfBirth_extraInitializers), __runInitializers(this, _gender_initializers, void 0));
                this.districtOfBirth = (__runInitializers(this, _gender_extraInitializers), __runInitializers(this, _districtOfBirth_initializers, void 0));
                this.taOfBirth = (__runInitializers(this, _districtOfBirth_extraInitializers), __runInitializers(this, _taOfBirth_initializers, void 0));
                this.villageOfBirth = (__runInitializers(this, _taOfBirth_extraInitializers), __runInitializers(this, _villageOfBirth_initializers, void 0));
                this.birthCertificateNo = (__runInitializers(this, _villageOfBirth_extraInitializers), __runInitializers(this, _birthCertificateNo_initializers, void 0));
                this.maritalStatus = (__runInitializers(this, _birthCertificateNo_extraInitializers), __runInitializers(this, _maritalStatus_initializers, void 0));
                this.eyeColor = (__runInitializers(this, _maritalStatus_extraInitializers), __runInitializers(this, _eyeColor_initializers, void 0));
                this.height = (__runInitializers(this, _eyeColor_extraInitializers), __runInitializers(this, _height_initializers, void 0));
                this.mobilePhone = (__runInitializers(this, _height_extraInitializers), __runInitializers(this, _mobilePhone_initializers, void 0));
                this.passportNo = (__runInitializers(this, _mobilePhone_extraInitializers), __runInitializers(this, _passportNo_initializers, void 0));
                this.disability = (__runInitializers(this, _passportNo_extraInitializers), __runInitializers(this, _disability_initializers, void 0));
                this.residentialDistrict = (__runInitializers(this, _disability_extraInitializers), __runInitializers(this, _residentialDistrict_initializers, void 0));
                this.residentialTA = (__runInitializers(this, _residentialDistrict_extraInitializers), __runInitializers(this, _residentialTA_initializers, void 0));
                this.residentialVillage = (__runInitializers(this, _residentialTA_extraInitializers), __runInitializers(this, _residentialVillage_initializers, void 0));
                this.permanentDistrict = (__runInitializers(this, _residentialVillage_extraInitializers), __runInitializers(this, _permanentDistrict_initializers, void 0));
                this.permanentTA = (__runInitializers(this, _permanentDistrict_extraInitializers), __runInitializers(this, _permanentTA_initializers, void 0));
                this.permanentVillage = (__runInitializers(this, _permanentTA_extraInitializers), __runInitializers(this, _permanentVillage_initializers, void 0));
                this.motherIdNo = (__runInitializers(this, _permanentVillage_extraInitializers), __runInitializers(this, _motherIdNo_initializers, void 0));
                this.motherFullName = (__runInitializers(this, _motherIdNo_extraInitializers), __runInitializers(this, _motherFullName_initializers, void 0));
                this.motherNationality = (__runInitializers(this, _motherFullName_extraInitializers), __runInitializers(this, _motherNationality_initializers, void 0));
                this.motherDistrict = (__runInitializers(this, _motherNationality_extraInitializers), __runInitializers(this, _motherDistrict_initializers, void 0));
                this.motherTA = (__runInitializers(this, _motherDistrict_extraInitializers), __runInitializers(this, _motherTA_initializers, void 0));
                this.motherVillage = (__runInitializers(this, _motherTA_extraInitializers), __runInitializers(this, _motherVillage_initializers, void 0));
                this.fatherIdNo = (__runInitializers(this, _motherVillage_extraInitializers), __runInitializers(this, _fatherIdNo_initializers, void 0));
                this.fatherFullName = (__runInitializers(this, _fatherIdNo_extraInitializers), __runInitializers(this, _fatherFullName_initializers, void 0));
                this.fatherNationality = (__runInitializers(this, _fatherFullName_extraInitializers), __runInitializers(this, _fatherNationality_initializers, void 0));
                this.fatherDistrict = (__runInitializers(this, _fatherNationality_extraInitializers), __runInitializers(this, _fatherDistrict_initializers, void 0));
                this.fatherTA = (__runInitializers(this, _fatherDistrict_extraInitializers), __runInitializers(this, _fatherTA_initializers, void 0));
                this.fatherVillage = (__runInitializers(this, _fatherTA_extraInitializers), __runInitializers(this, _fatherVillage_initializers, void 0));
                this.firstWitnessIdNo = (__runInitializers(this, _fatherVillage_extraInitializers), __runInitializers(this, _firstWitnessIdNo_initializers, void 0));
                this.secondWitnessIdNo = (__runInitializers(this, _firstWitnessIdNo_extraInitializers), __runInitializers(this, _secondWitnessIdNo_initializers, void 0));
                __runInitializers(this, _secondWitnessIdNo_extraInitializers);
            }
            return CreateNationalIdDto;
        }()),
        (function () {
            var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
            _firstName_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.Length)(1, 50)];
            _otherNames_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.IsOptional)()];
            _surname_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.Length)(1, 50)];
            _nationality_decorators = [(0, class_validator_1.IsString)()];
            _secondNationality_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.IsOptional)()];
            _dateOfBirth_decorators = [(0, class_transformer_1.Type)(function () { return Date; }), (0, class_validator_1.IsDate)()];
            _gender_decorators = [(0, class_validator_1.IsEnum)(Gender)];
            _districtOfBirth_decorators = [(0, class_validator_1.IsString)()];
            _taOfBirth_decorators = [(0, class_validator_1.IsString)()];
            _villageOfBirth_decorators = [(0, class_validator_1.IsString)()];
            _birthCertificateNo_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.IsOptional)()];
            _maritalStatus_decorators = [(0, class_validator_1.IsEnum)(MaritalStatus)];
            _eyeColor_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.IsOptional)()];
            _height_decorators = [(0, class_validator_1.IsNumber)(), (0, class_validator_1.IsOptional)(), (0, class_validator_1.Min)(0.5), (0, class_validator_1.Max)(2.5)];
            _mobilePhone_decorators = [(0, class_validator_1.IsPhoneNumber)(), (0, class_validator_1.IsOptional)()];
            _passportNo_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.IsOptional)()];
            _disability_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.IsOptional)()];
            _residentialDistrict_decorators = [(0, class_validator_1.IsString)()];
            _residentialTA_decorators = [(0, class_validator_1.IsString)()];
            _residentialVillage_decorators = [(0, class_validator_1.IsString)()];
            _permanentDistrict_decorators = [(0, class_validator_1.IsString)()];
            _permanentTA_decorators = [(0, class_validator_1.IsString)()];
            _permanentVillage_decorators = [(0, class_validator_1.IsString)()];
            _motherIdNo_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.IsOptional)()];
            _motherFullName_decorators = [(0, class_validator_1.IsString)()];
            _motherNationality_decorators = [(0, class_validator_1.IsString)()];
            _motherDistrict_decorators = [(0, class_validator_1.IsString)()];
            _motherTA_decorators = [(0, class_validator_1.IsString)()];
            _motherVillage_decorators = [(0, class_validator_1.IsString)()];
            _fatherIdNo_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.IsOptional)()];
            _fatherFullName_decorators = [(0, class_validator_1.IsString)()];
            _fatherNationality_decorators = [(0, class_validator_1.IsString)()];
            _fatherDistrict_decorators = [(0, class_validator_1.IsString)()];
            _fatherTA_decorators = [(0, class_validator_1.IsString)()];
            _fatherVillage_decorators = [(0, class_validator_1.IsString)()];
            _firstWitnessIdNo_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.Length)(8, 15)];
            _secondWitnessIdNo_decorators = [(0, class_validator_1.IsString)(), (0, class_validator_1.Length)(8, 15)];
            __esDecorate(null, null, _firstName_decorators, { kind: "field", name: "firstName", static: false, private: false, access: { has: function (obj) { return "firstName" in obj; }, get: function (obj) { return obj.firstName; }, set: function (obj, value) { obj.firstName = value; } }, metadata: _metadata }, _firstName_initializers, _firstName_extraInitializers);
            __esDecorate(null, null, _otherNames_decorators, { kind: "field", name: "otherNames", static: false, private: false, access: { has: function (obj) { return "otherNames" in obj; }, get: function (obj) { return obj.otherNames; }, set: function (obj, value) { obj.otherNames = value; } }, metadata: _metadata }, _otherNames_initializers, _otherNames_extraInitializers);
            __esDecorate(null, null, _surname_decorators, { kind: "field", name: "surname", static: false, private: false, access: { has: function (obj) { return "surname" in obj; }, get: function (obj) { return obj.surname; }, set: function (obj, value) { obj.surname = value; } }, metadata: _metadata }, _surname_initializers, _surname_extraInitializers);
            __esDecorate(null, null, _nationality_decorators, { kind: "field", name: "nationality", static: false, private: false, access: { has: function (obj) { return "nationality" in obj; }, get: function (obj) { return obj.nationality; }, set: function (obj, value) { obj.nationality = value; } }, metadata: _metadata }, _nationality_initializers, _nationality_extraInitializers);
            __esDecorate(null, null, _secondNationality_decorators, { kind: "field", name: "secondNationality", static: false, private: false, access: { has: function (obj) { return "secondNationality" in obj; }, get: function (obj) { return obj.secondNationality; }, set: function (obj, value) { obj.secondNationality = value; } }, metadata: _metadata }, _secondNationality_initializers, _secondNationality_extraInitializers);
            __esDecorate(null, null, _dateOfBirth_decorators, { kind: "field", name: "dateOfBirth", static: false, private: false, access: { has: function (obj) { return "dateOfBirth" in obj; }, get: function (obj) { return obj.dateOfBirth; }, set: function (obj, value) { obj.dateOfBirth = value; } }, metadata: _metadata }, _dateOfBirth_initializers, _dateOfBirth_extraInitializers);
            __esDecorate(null, null, _gender_decorators, { kind: "field", name: "gender", static: false, private: false, access: { has: function (obj) { return "gender" in obj; }, get: function (obj) { return obj.gender; }, set: function (obj, value) { obj.gender = value; } }, metadata: _metadata }, _gender_initializers, _gender_extraInitializers);
            __esDecorate(null, null, _districtOfBirth_decorators, { kind: "field", name: "districtOfBirth", static: false, private: false, access: { has: function (obj) { return "districtOfBirth" in obj; }, get: function (obj) { return obj.districtOfBirth; }, set: function (obj, value) { obj.districtOfBirth = value; } }, metadata: _metadata }, _districtOfBirth_initializers, _districtOfBirth_extraInitializers);
            __esDecorate(null, null, _taOfBirth_decorators, { kind: "field", name: "taOfBirth", static: false, private: false, access: { has: function (obj) { return "taOfBirth" in obj; }, get: function (obj) { return obj.taOfBirth; }, set: function (obj, value) { obj.taOfBirth = value; } }, metadata: _metadata }, _taOfBirth_initializers, _taOfBirth_extraInitializers);
            __esDecorate(null, null, _villageOfBirth_decorators, { kind: "field", name: "villageOfBirth", static: false, private: false, access: { has: function (obj) { return "villageOfBirth" in obj; }, get: function (obj) { return obj.villageOfBirth; }, set: function (obj, value) { obj.villageOfBirth = value; } }, metadata: _metadata }, _villageOfBirth_initializers, _villageOfBirth_extraInitializers);
            __esDecorate(null, null, _birthCertificateNo_decorators, { kind: "field", name: "birthCertificateNo", static: false, private: false, access: { has: function (obj) { return "birthCertificateNo" in obj; }, get: function (obj) { return obj.birthCertificateNo; }, set: function (obj, value) { obj.birthCertificateNo = value; } }, metadata: _metadata }, _birthCertificateNo_initializers, _birthCertificateNo_extraInitializers);
            __esDecorate(null, null, _maritalStatus_decorators, { kind: "field", name: "maritalStatus", static: false, private: false, access: { has: function (obj) { return "maritalStatus" in obj; }, get: function (obj) { return obj.maritalStatus; }, set: function (obj, value) { obj.maritalStatus = value; } }, metadata: _metadata }, _maritalStatus_initializers, _maritalStatus_extraInitializers);
            __esDecorate(null, null, _eyeColor_decorators, { kind: "field", name: "eyeColor", static: false, private: false, access: { has: function (obj) { return "eyeColor" in obj; }, get: function (obj) { return obj.eyeColor; }, set: function (obj, value) { obj.eyeColor = value; } }, metadata: _metadata }, _eyeColor_initializers, _eyeColor_extraInitializers);
            __esDecorate(null, null, _height_decorators, { kind: "field", name: "height", static: false, private: false, access: { has: function (obj) { return "height" in obj; }, get: function (obj) { return obj.height; }, set: function (obj, value) { obj.height = value; } }, metadata: _metadata }, _height_initializers, _height_extraInitializers);
            __esDecorate(null, null, _mobilePhone_decorators, { kind: "field", name: "mobilePhone", static: false, private: false, access: { has: function (obj) { return "mobilePhone" in obj; }, get: function (obj) { return obj.mobilePhone; }, set: function (obj, value) { obj.mobilePhone = value; } }, metadata: _metadata }, _mobilePhone_initializers, _mobilePhone_extraInitializers);
            __esDecorate(null, null, _passportNo_decorators, { kind: "field", name: "passportNo", static: false, private: false, access: { has: function (obj) { return "passportNo" in obj; }, get: function (obj) { return obj.passportNo; }, set: function (obj, value) { obj.passportNo = value; } }, metadata: _metadata }, _passportNo_initializers, _passportNo_extraInitializers);
            __esDecorate(null, null, _disability_decorators, { kind: "field", name: "disability", static: false, private: false, access: { has: function (obj) { return "disability" in obj; }, get: function (obj) { return obj.disability; }, set: function (obj, value) { obj.disability = value; } }, metadata: _metadata }, _disability_initializers, _disability_extraInitializers);
            __esDecorate(null, null, _residentialDistrict_decorators, { kind: "field", name: "residentialDistrict", static: false, private: false, access: { has: function (obj) { return "residentialDistrict" in obj; }, get: function (obj) { return obj.residentialDistrict; }, set: function (obj, value) { obj.residentialDistrict = value; } }, metadata: _metadata }, _residentialDistrict_initializers, _residentialDistrict_extraInitializers);
            __esDecorate(null, null, _residentialTA_decorators, { kind: "field", name: "residentialTA", static: false, private: false, access: { has: function (obj) { return "residentialTA" in obj; }, get: function (obj) { return obj.residentialTA; }, set: function (obj, value) { obj.residentialTA = value; } }, metadata: _metadata }, _residentialTA_initializers, _residentialTA_extraInitializers);
            __esDecorate(null, null, _residentialVillage_decorators, { kind: "field", name: "residentialVillage", static: false, private: false, access: { has: function (obj) { return "residentialVillage" in obj; }, get: function (obj) { return obj.residentialVillage; }, set: function (obj, value) { obj.residentialVillage = value; } }, metadata: _metadata }, _residentialVillage_initializers, _residentialVillage_extraInitializers);
            __esDecorate(null, null, _permanentDistrict_decorators, { kind: "field", name: "permanentDistrict", static: false, private: false, access: { has: function (obj) { return "permanentDistrict" in obj; }, get: function (obj) { return obj.permanentDistrict; }, set: function (obj, value) { obj.permanentDistrict = value; } }, metadata: _metadata }, _permanentDistrict_initializers, _permanentDistrict_extraInitializers);
            __esDecorate(null, null, _permanentTA_decorators, { kind: "field", name: "permanentTA", static: false, private: false, access: { has: function (obj) { return "permanentTA" in obj; }, get: function (obj) { return obj.permanentTA; }, set: function (obj, value) { obj.permanentTA = value; } }, metadata: _metadata }, _permanentTA_initializers, _permanentTA_extraInitializers);
            __esDecorate(null, null, _permanentVillage_decorators, { kind: "field", name: "permanentVillage", static: false, private: false, access: { has: function (obj) { return "permanentVillage" in obj; }, get: function (obj) { return obj.permanentVillage; }, set: function (obj, value) { obj.permanentVillage = value; } }, metadata: _metadata }, _permanentVillage_initializers, _permanentVillage_extraInitializers);
            __esDecorate(null, null, _motherIdNo_decorators, { kind: "field", name: "motherIdNo", static: false, private: false, access: { has: function (obj) { return "motherIdNo" in obj; }, get: function (obj) { return obj.motherIdNo; }, set: function (obj, value) { obj.motherIdNo = value; } }, metadata: _metadata }, _motherIdNo_initializers, _motherIdNo_extraInitializers);
            __esDecorate(null, null, _motherFullName_decorators, { kind: "field", name: "motherFullName", static: false, private: false, access: { has: function (obj) { return "motherFullName" in obj; }, get: function (obj) { return obj.motherFullName; }, set: function (obj, value) { obj.motherFullName = value; } }, metadata: _metadata }, _motherFullName_initializers, _motherFullName_extraInitializers);
            __esDecorate(null, null, _motherNationality_decorators, { kind: "field", name: "motherNationality", static: false, private: false, access: { has: function (obj) { return "motherNationality" in obj; }, get: function (obj) { return obj.motherNationality; }, set: function (obj, value) { obj.motherNationality = value; } }, metadata: _metadata }, _motherNationality_initializers, _motherNationality_extraInitializers);
            __esDecorate(null, null, _motherDistrict_decorators, { kind: "field", name: "motherDistrict", static: false, private: false, access: { has: function (obj) { return "motherDistrict" in obj; }, get: function (obj) { return obj.motherDistrict; }, set: function (obj, value) { obj.motherDistrict = value; } }, metadata: _metadata }, _motherDistrict_initializers, _motherDistrict_extraInitializers);
            __esDecorate(null, null, _motherTA_decorators, { kind: "field", name: "motherTA", static: false, private: false, access: { has: function (obj) { return "motherTA" in obj; }, get: function (obj) { return obj.motherTA; }, set: function (obj, value) { obj.motherTA = value; } }, metadata: _metadata }, _motherTA_initializers, _motherTA_extraInitializers);
            __esDecorate(null, null, _motherVillage_decorators, { kind: "field", name: "motherVillage", static: false, private: false, access: { has: function (obj) { return "motherVillage" in obj; }, get: function (obj) { return obj.motherVillage; }, set: function (obj, value) { obj.motherVillage = value; } }, metadata: _metadata }, _motherVillage_initializers, _motherVillage_extraInitializers);
            __esDecorate(null, null, _fatherIdNo_decorators, { kind: "field", name: "fatherIdNo", static: false, private: false, access: { has: function (obj) { return "fatherIdNo" in obj; }, get: function (obj) { return obj.fatherIdNo; }, set: function (obj, value) { obj.fatherIdNo = value; } }, metadata: _metadata }, _fatherIdNo_initializers, _fatherIdNo_extraInitializers);
            __esDecorate(null, null, _fatherFullName_decorators, { kind: "field", name: "fatherFullName", static: false, private: false, access: { has: function (obj) { return "fatherFullName" in obj; }, get: function (obj) { return obj.fatherFullName; }, set: function (obj, value) { obj.fatherFullName = value; } }, metadata: _metadata }, _fatherFullName_initializers, _fatherFullName_extraInitializers);
            __esDecorate(null, null, _fatherNationality_decorators, { kind: "field", name: "fatherNationality", static: false, private: false, access: { has: function (obj) { return "fatherNationality" in obj; }, get: function (obj) { return obj.fatherNationality; }, set: function (obj, value) { obj.fatherNationality = value; } }, metadata: _metadata }, _fatherNationality_initializers, _fatherNationality_extraInitializers);
            __esDecorate(null, null, _fatherDistrict_decorators, { kind: "field", name: "fatherDistrict", static: false, private: false, access: { has: function (obj) { return "fatherDistrict" in obj; }, get: function (obj) { return obj.fatherDistrict; }, set: function (obj, value) { obj.fatherDistrict = value; } }, metadata: _metadata }, _fatherDistrict_initializers, _fatherDistrict_extraInitializers);
            __esDecorate(null, null, _fatherTA_decorators, { kind: "field", name: "fatherTA", static: false, private: false, access: { has: function (obj) { return "fatherTA" in obj; }, get: function (obj) { return obj.fatherTA; }, set: function (obj, value) { obj.fatherTA = value; } }, metadata: _metadata }, _fatherTA_initializers, _fatherTA_extraInitializers);
            __esDecorate(null, null, _fatherVillage_decorators, { kind: "field", name: "fatherVillage", static: false, private: false, access: { has: function (obj) { return "fatherVillage" in obj; }, get: function (obj) { return obj.fatherVillage; }, set: function (obj, value) { obj.fatherVillage = value; } }, metadata: _metadata }, _fatherVillage_initializers, _fatherVillage_extraInitializers);
            __esDecorate(null, null, _firstWitnessIdNo_decorators, { kind: "field", name: "firstWitnessIdNo", static: false, private: false, access: { has: function (obj) { return "firstWitnessIdNo" in obj; }, get: function (obj) { return obj.firstWitnessIdNo; }, set: function (obj, value) { obj.firstWitnessIdNo = value; } }, metadata: _metadata }, _firstWitnessIdNo_initializers, _firstWitnessIdNo_extraInitializers);
            __esDecorate(null, null, _secondWitnessIdNo_decorators, { kind: "field", name: "secondWitnessIdNo", static: false, private: false, access: { has: function (obj) { return "secondWitnessIdNo" in obj; }, get: function (obj) { return obj.secondWitnessIdNo; }, set: function (obj, value) { obj.secondWitnessIdNo = value; } }, metadata: _metadata }, _secondWitnessIdNo_initializers, _secondWitnessIdNo_extraInitializers);
            if (_metadata) Object.defineProperty(_a, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        })(),
        _a;
}();
exports.CreateNationalIdDto = CreateNationalIdDto;
