"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeathCertificate = void 0;
var typeorm_1 = require("typeorm");
var DeathCertificate = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('death_certificates')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _certificateNumber_decorators;
    var _certificateNumber_initializers = [];
    var _certificateNumber_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var _surname_decorators;
    var _surname_initializers = [];
    var _surname_extraInitializers = [];
    var _firstName_decorators;
    var _firstName_initializers = [];
    var _firstName_extraInitializers = [];
    var _otherNames_decorators;
    var _otherNames_initializers = [];
    var _otherNames_extraInitializers = [];
    var _deceasedFirstName_decorators;
    var _deceasedFirstName_initializers = [];
    var _deceasedFirstName_extraInitializers = [];
    var _deceasedLastName_decorators;
    var _deceasedLastName_initializers = [];
    var _deceasedLastName_extraInitializers = [];
    var _idNumber_decorators;
    var _idNumber_initializers = [];
    var _idNumber_extraInitializers = [];
    var _deceasedNationalId_decorators;
    var _deceasedNationalId_initializers = [];
    var _deceasedNationalId_extraInitializers = [];
    var _nationality_decorators;
    var _nationality_initializers = [];
    var _nationality_extraInitializers = [];
    var _gender_decorators;
    var _gender_initializers = [];
    var _gender_extraInitializers = [];
    var _dateOfBirth_decorators;
    var _dateOfBirth_initializers = [];
    var _dateOfBirth_extraInitializers = [];
    var _dateOfDeath_decorators;
    var _dateOfDeath_initializers = [];
    var _dateOfDeath_extraInitializers = [];
    var _causeOfDeath_decorators;
    var _causeOfDeath_initializers = [];
    var _causeOfDeath_extraInitializers = [];
    var _placeOfDeath_decorators;
    var _placeOfDeath_initializers = [];
    var _placeOfDeath_extraInitializers = [];
    var _healthFacilityName_decorators;
    var _healthFacilityName_initializers = [];
    var _healthFacilityName_extraInitializers = [];
    var _healthFacilityAddress_decorators;
    var _healthFacilityAddress_initializers = [];
    var _healthFacilityAddress_extraInitializers = [];
    var _homeDistrict_decorators;
    var _homeDistrict_initializers = [];
    var _homeDistrict_extraInitializers = [];
    var _homeTA_decorators;
    var _homeTA_initializers = [];
    var _homeTA_extraInitializers = [];
    var _homeVillage_decorators;
    var _homeVillage_initializers = [];
    var _homeVillage_extraInitializers = [];
    var _otherPlaceDetails_decorators;
    var _otherPlaceDetails_initializers = [];
    var _otherPlaceDetails_extraInitializers = [];
    var _mannerOfDeath_decorators;
    var _mannerOfDeath_initializers = [];
    var _mannerOfDeath_extraInitializers = [];
    var _accidentType_decorators;
    var _accidentType_initializers = [];
    var _accidentType_extraInitializers = [];
    var _accidentDetails_decorators;
    var _accidentDetails_initializers = [];
    var _accidentDetails_extraInitializers = [];
    var _residentialDistrict_decorators;
    var _residentialDistrict_initializers = [];
    var _residentialDistrict_extraInitializers = [];
    var _residentialTA_decorators;
    var _residentialTA_initializers = [];
    var _residentialTA_extraInitializers = [];
    var _residentialVillage_decorators;
    var _residentialVillage_initializers = [];
    var _residentialVillage_extraInitializers = [];
    var _wasPregnant_decorators;
    var _wasPregnant_initializers = [];
    var _wasPregnant_extraInitializers = [];
    var _pregnantAtDeath_decorators;
    var _pregnantAtDeath_initializers = [];
    var _pregnantAtDeath_extraInitializers = [];
    var _motherSurname_decorators;
    var _motherSurname_initializers = [];
    var _motherSurname_extraInitializers = [];
    var _motherFirstName_decorators;
    var _motherFirstName_initializers = [];
    var _motherFirstName_extraInitializers = [];
    var _motherOtherNames_decorators;
    var _motherOtherNames_initializers = [];
    var _motherOtherNames_extraInitializers = [];
    var _motherIdNo_decorators;
    var _motherIdNo_initializers = [];
    var _motherIdNo_extraInitializers = [];
    var _motherNationality_decorators;
    var _motherNationality_initializers = [];
    var _motherNationality_extraInitializers = [];
    var _fatherSurname_decorators;
    var _fatherSurname_initializers = [];
    var _fatherSurname_extraInitializers = [];
    var _fatherFirstName_decorators;
    var _fatherFirstName_initializers = [];
    var _fatherFirstName_extraInitializers = [];
    var _fatherOtherNames_decorators;
    var _fatherOtherNames_initializers = [];
    var _fatherOtherNames_extraInitializers = [];
    var _fatherIdNo_decorators;
    var _fatherIdNo_initializers = [];
    var _fatherIdNo_extraInitializers = [];
    var _fatherNationality_decorators;
    var _fatherNationality_initializers = [];
    var _fatherNationality_extraInitializers = [];
    var _informantSurname_decorators;
    var _informantSurname_initializers = [];
    var _informantSurname_extraInitializers = [];
    var _informantFirstName_decorators;
    var _informantFirstName_initializers = [];
    var _informantFirstName_extraInitializers = [];
    var _informantOtherNames_decorators;
    var _informantOtherNames_initializers = [];
    var _informantOtherNames_extraInitializers = [];
    var _informantIdNo_decorators;
    var _informantIdNo_initializers = [];
    var _informantIdNo_extraInitializers = [];
    var _informantName_decorators;
    var _informantName_initializers = [];
    var _informantName_extraInitializers = [];
    var _informantRelation_decorators;
    var _informantRelation_initializers = [];
    var _informantRelation_extraInitializers = [];
    var _informantRelationship_decorators;
    var _informantRelationship_initializers = [];
    var _informantRelationship_extraInitializers = [];
    var _informantAddress_decorators;
    var _informantAddress_initializers = [];
    var _informantAddress_extraInitializers = [];
    var _informantPostalAddress_decorators;
    var _informantPostalAddress_initializers = [];
    var _informantPostalAddress_extraInitializers = [];
    var _informantPhone_decorators;
    var _informantPhone_initializers = [];
    var _informantPhone_extraInitializers = [];
    var _informantSignature_decorators;
    var _informantSignature_initializers = [];
    var _informantSignature_extraInitializers = [];
    var _informantDate_decorators;
    var _informantDate_initializers = [];
    var _informantDate_extraInitializers = [];
    var _villageHeadName_decorators;
    var _villageHeadName_initializers = [];
    var _villageHeadName_extraInitializers = [];
    var _villageHeadIdNo_decorators;
    var _villageHeadIdNo_initializers = [];
    var _villageHeadIdNo_extraInitializers = [];
    var _villageHeadSignature_decorators;
    var _villageHeadSignature_initializers = [];
    var _villageHeadSignature_extraInitializers = [];
    var _villageHeadDate_decorators;
    var _villageHeadDate_initializers = [];
    var _villageHeadDate_extraInitializers = [];
    var _villageHeadStamp_decorators;
    var _villageHeadStamp_initializers = [];
    var _villageHeadStamp_extraInitializers = [];
    var _certificatePdfUrl_decorators;
    var _certificatePdfUrl_initializers = [];
    var _certificatePdfUrl_extraInitializers = [];
    var _isValid_decorators;
    var _isValid_initializers = [];
    var _isValid_extraInitializers = [];
    var _issuedAt_decorators;
    var _issuedAt_initializers = [];
    var _issuedAt_extraInitializers = [];
    var _issuedBy_decorators;
    var _issuedBy_initializers = [];
    var _issuedBy_extraInitializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _status_extraInitializers = [];
    var _districtRegistrarSignature_decorators;
    var _districtRegistrarSignature_initializers = [];
    var _districtRegistrarSignature_extraInitializers = [];
    var _dateOfRegistration_decorators;
    var _dateOfRegistration_initializers = [];
    var _dateOfRegistration_extraInitializers = [];
    var _deathEntryNumber_decorators;
    var _deathEntryNumber_initializers = [];
    var _deathEntryNumber_extraInitializers = [];
    var _officialStamp_decorators;
    var _officialStamp_initializers = [];
    var _officialStamp_extraInitializers = [];
    var DeathCertificate = _classThis = /** @class */ (function () {
        function DeathCertificate_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.certificateNumber = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _certificateNumber_initializers, void 0));
            this.createdAt = (__runInitializers(this, _certificateNumber_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            // Deceased Details
            this.surname = (__runInitializers(this, _updatedAt_extraInitializers), __runInitializers(this, _surname_initializers, void 0));
            this.firstName = (__runInitializers(this, _surname_extraInitializers), __runInitializers(this, _firstName_initializers, void 0));
            this.otherNames = (__runInitializers(this, _firstName_extraInitializers), __runInitializers(this, _otherNames_initializers, void 0));
            this.deceasedFirstName = (__runInitializers(this, _otherNames_extraInitializers), __runInitializers(this, _deceasedFirstName_initializers, void 0));
            this.deceasedLastName = (__runInitializers(this, _deceasedFirstName_extraInitializers), __runInitializers(this, _deceasedLastName_initializers, void 0));
            this.idNumber = (__runInitializers(this, _deceasedLastName_extraInitializers), __runInitializers(this, _idNumber_initializers, void 0));
            this.deceasedNationalId = (__runInitializers(this, _idNumber_extraInitializers), __runInitializers(this, _deceasedNationalId_initializers, void 0));
            this.nationality = (__runInitializers(this, _deceasedNationalId_extraInitializers), __runInitializers(this, _nationality_initializers, void 0));
            this.gender = (__runInitializers(this, _nationality_extraInitializers), __runInitializers(this, _gender_initializers, void 0));
            this.dateOfBirth = (__runInitializers(this, _gender_extraInitializers), __runInitializers(this, _dateOfBirth_initializers, void 0));
            this.dateOfDeath = (__runInitializers(this, _dateOfBirth_extraInitializers), __runInitializers(this, _dateOfDeath_initializers, void 0));
            this.causeOfDeath = (__runInitializers(this, _dateOfDeath_extraInitializers), __runInitializers(this, _causeOfDeath_initializers, void 0));
            this.placeOfDeath = (__runInitializers(this, _causeOfDeath_extraInitializers), __runInitializers(this, _placeOfDeath_initializers, void 0));
            this.healthFacilityName = (__runInitializers(this, _placeOfDeath_extraInitializers), __runInitializers(this, _healthFacilityName_initializers, void 0));
            this.healthFacilityAddress = (__runInitializers(this, _healthFacilityName_extraInitializers), __runInitializers(this, _healthFacilityAddress_initializers, void 0));
            this.homeDistrict = (__runInitializers(this, _healthFacilityAddress_extraInitializers), __runInitializers(this, _homeDistrict_initializers, void 0));
            this.homeTA = (__runInitializers(this, _homeDistrict_extraInitializers), __runInitializers(this, _homeTA_initializers, void 0));
            this.homeVillage = (__runInitializers(this, _homeTA_extraInitializers), __runInitializers(this, _homeVillage_initializers, void 0));
            this.otherPlaceDetails = (__runInitializers(this, _homeVillage_extraInitializers), __runInitializers(this, _otherPlaceDetails_initializers, void 0));
            this.mannerOfDeath = (__runInitializers(this, _otherPlaceDetails_extraInitializers), __runInitializers(this, _mannerOfDeath_initializers, void 0));
            this.accidentType = (__runInitializers(this, _mannerOfDeath_extraInitializers), __runInitializers(this, _accidentType_initializers, void 0));
            this.accidentDetails = (__runInitializers(this, _accidentType_extraInitializers), __runInitializers(this, _accidentDetails_initializers, void 0));
            // Residential Address
            this.residentialDistrict = (__runInitializers(this, _accidentDetails_extraInitializers), __runInitializers(this, _residentialDistrict_initializers, void 0));
            this.residentialTA = (__runInitializers(this, _residentialDistrict_extraInitializers), __runInitializers(this, _residentialTA_initializers, void 0));
            this.residentialVillage = (__runInitializers(this, _residentialTA_extraInitializers), __runInitializers(this, _residentialVillage_initializers, void 0));
            // Pregnancy
            this.wasPregnant = (__runInitializers(this, _residentialVillage_extraInitializers), __runInitializers(this, _wasPregnant_initializers, void 0));
            this.pregnantAtDeath = (__runInitializers(this, _wasPregnant_extraInitializers), __runInitializers(this, _pregnantAtDeath_initializers, void 0));
            // Mother Details
            this.motherSurname = (__runInitializers(this, _pregnantAtDeath_extraInitializers), __runInitializers(this, _motherSurname_initializers, void 0));
            this.motherFirstName = (__runInitializers(this, _motherSurname_extraInitializers), __runInitializers(this, _motherFirstName_initializers, void 0));
            this.motherOtherNames = (__runInitializers(this, _motherFirstName_extraInitializers), __runInitializers(this, _motherOtherNames_initializers, void 0));
            this.motherIdNo = (__runInitializers(this, _motherOtherNames_extraInitializers), __runInitializers(this, _motherIdNo_initializers, void 0));
            this.motherNationality = (__runInitializers(this, _motherIdNo_extraInitializers), __runInitializers(this, _motherNationality_initializers, void 0));
            // Father Details
            this.fatherSurname = (__runInitializers(this, _motherNationality_extraInitializers), __runInitializers(this, _fatherSurname_initializers, void 0));
            this.fatherFirstName = (__runInitializers(this, _fatherSurname_extraInitializers), __runInitializers(this, _fatherFirstName_initializers, void 0));
            this.fatherOtherNames = (__runInitializers(this, _fatherFirstName_extraInitializers), __runInitializers(this, _fatherOtherNames_initializers, void 0));
            this.fatherIdNo = (__runInitializers(this, _fatherOtherNames_extraInitializers), __runInitializers(this, _fatherIdNo_initializers, void 0));
            this.fatherNationality = (__runInitializers(this, _fatherIdNo_extraInitializers), __runInitializers(this, _fatherNationality_initializers, void 0));
            // Informant Details
            this.informantSurname = (__runInitializers(this, _fatherNationality_extraInitializers), __runInitializers(this, _informantSurname_initializers, void 0));
            this.informantFirstName = (__runInitializers(this, _informantSurname_extraInitializers), __runInitializers(this, _informantFirstName_initializers, void 0));
            this.informantOtherNames = (__runInitializers(this, _informantFirstName_extraInitializers), __runInitializers(this, _informantOtherNames_initializers, void 0));
            this.informantIdNo = (__runInitializers(this, _informantOtherNames_extraInitializers), __runInitializers(this, _informantIdNo_initializers, void 0));
            this.informantName = (__runInitializers(this, _informantIdNo_extraInitializers), __runInitializers(this, _informantName_initializers, void 0));
            this.informantRelation = (__runInitializers(this, _informantName_extraInitializers), __runInitializers(this, _informantRelation_initializers, void 0));
            this.informantRelationship = (__runInitializers(this, _informantRelation_extraInitializers), __runInitializers(this, _informantRelationship_initializers, void 0));
            this.informantAddress = (__runInitializers(this, _informantRelationship_extraInitializers), __runInitializers(this, _informantAddress_initializers, void 0));
            this.informantPostalAddress = (__runInitializers(this, _informantAddress_extraInitializers), __runInitializers(this, _informantPostalAddress_initializers, void 0));
            this.informantPhone = (__runInitializers(this, _informantPostalAddress_extraInitializers), __runInitializers(this, _informantPhone_initializers, void 0));
            this.informantSignature = (__runInitializers(this, _informantPhone_extraInitializers), __runInitializers(this, _informantSignature_initializers, void 0));
            this.informantDate = (__runInitializers(this, _informantSignature_extraInitializers), __runInitializers(this, _informantDate_initializers, void 0));
            // Village Head Verification
            this.villageHeadName = (__runInitializers(this, _informantDate_extraInitializers), __runInitializers(this, _villageHeadName_initializers, void 0));
            this.villageHeadIdNo = (__runInitializers(this, _villageHeadName_extraInitializers), __runInitializers(this, _villageHeadIdNo_initializers, void 0));
            this.villageHeadSignature = (__runInitializers(this, _villageHeadIdNo_extraInitializers), __runInitializers(this, _villageHeadSignature_initializers, void 0));
            this.villageHeadDate = (__runInitializers(this, _villageHeadSignature_extraInitializers), __runInitializers(this, _villageHeadDate_initializers, void 0));
            this.villageHeadStamp = (__runInitializers(this, _villageHeadDate_extraInitializers), __runInitializers(this, _villageHeadStamp_initializers, void 0));
            // Certificate Details
            this.certificatePdfUrl = (__runInitializers(this, _villageHeadStamp_extraInitializers), __runInitializers(this, _certificatePdfUrl_initializers, void 0));
            this.isValid = (__runInitializers(this, _certificatePdfUrl_extraInitializers), __runInitializers(this, _isValid_initializers, void 0));
            this.issuedAt = (__runInitializers(this, _isValid_extraInitializers), __runInitializers(this, _issuedAt_initializers, void 0));
            this.issuedBy = (__runInitializers(this, _issuedAt_extraInitializers), __runInitializers(this, _issuedBy_initializers, void 0));
            // Status
            this.status = (__runInitializers(this, _issuedBy_extraInitializers), __runInitializers(this, _status_initializers, void 0));
            // Official Use
            this.districtRegistrarSignature = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _districtRegistrarSignature_initializers, void 0));
            this.dateOfRegistration = (__runInitializers(this, _districtRegistrarSignature_extraInitializers), __runInitializers(this, _dateOfRegistration_initializers, void 0));
            this.deathEntryNumber = (__runInitializers(this, _dateOfRegistration_extraInitializers), __runInitializers(this, _deathEntryNumber_initializers, void 0));
            this.officialStamp = (__runInitializers(this, _deathEntryNumber_extraInitializers), __runInitializers(this, _officialStamp_initializers, void 0));
            __runInitializers(this, _officialStamp_extraInitializers);
        }
        return DeathCertificate_1;
    }());
    __setFunctionName(_classThis, "DeathCertificate");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _certificateNumber_decorators = [(0, typeorm_1.Column)({ unique: true })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)()];
        _surname_decorators = [(0, typeorm_1.Column)()];
        _firstName_decorators = [(0, typeorm_1.Column)()];
        _otherNames_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _deceasedFirstName_decorators = [(0, typeorm_1.Column)()];
        _deceasedLastName_decorators = [(0, typeorm_1.Column)()];
        _idNumber_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _deceasedNationalId_decorators = [(0, typeorm_1.Column)()];
        _nationality_decorators = [(0, typeorm_1.Column)()];
        _gender_decorators = [(0, typeorm_1.Column)()];
        _dateOfBirth_decorators = [(0, typeorm_1.Column)({ type: 'date' })];
        _dateOfDeath_decorators = [(0, typeorm_1.Column)({ type: 'date' })];
        _causeOfDeath_decorators = [(0, typeorm_1.Column)()];
        _placeOfDeath_decorators = [(0, typeorm_1.Column)()];
        _healthFacilityName_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _healthFacilityAddress_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'text' })];
        _homeDistrict_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _homeTA_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _homeVillage_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _otherPlaceDetails_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'text' })];
        _mannerOfDeath_decorators = [(0, typeorm_1.Column)()];
        _accidentType_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _accidentDetails_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'text' })];
        _residentialDistrict_decorators = [(0, typeorm_1.Column)()];
        _residentialTA_decorators = [(0, typeorm_1.Column)()];
        _residentialVillage_decorators = [(0, typeorm_1.Column)()];
        _wasPregnant_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _pregnantAtDeath_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'boolean' })];
        _motherSurname_decorators = [(0, typeorm_1.Column)()];
        _motherFirstName_decorators = [(0, typeorm_1.Column)()];
        _motherOtherNames_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _motherIdNo_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _motherNationality_decorators = [(0, typeorm_1.Column)()];
        _fatherSurname_decorators = [(0, typeorm_1.Column)()];
        _fatherFirstName_decorators = [(0, typeorm_1.Column)()];
        _fatherOtherNames_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _fatherIdNo_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _fatherNationality_decorators = [(0, typeorm_1.Column)()];
        _informantSurname_decorators = [(0, typeorm_1.Column)()];
        _informantFirstName_decorators = [(0, typeorm_1.Column)()];
        _informantOtherNames_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _informantIdNo_decorators = [(0, typeorm_1.Column)()];
        _informantName_decorators = [(0, typeorm_1.Column)()];
        _informantRelation_decorators = [(0, typeorm_1.Column)()];
        _informantRelationship_decorators = [(0, typeorm_1.Column)()];
        _informantAddress_decorators = [(0, typeorm_1.Column)({ type: 'text' })];
        _informantPostalAddress_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'text' })];
        _informantPhone_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _informantSignature_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'text' })];
        _informantDate_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'timestamp' })];
        _villageHeadName_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _villageHeadIdNo_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _villageHeadSignature_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'text' })];
        _villageHeadDate_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'timestamp' })];
        _villageHeadStamp_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'text' })];
        _certificatePdfUrl_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _isValid_decorators = [(0, typeorm_1.Column)({ default: true })];
        _issuedAt_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'timestamp' })];
        _issuedBy_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _status_decorators = [(0, typeorm_1.Column)({ default: 'PENDING' })];
        _districtRegistrarSignature_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'text' })];
        _dateOfRegistration_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'timestamp' })];
        _deathEntryNumber_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _officialStamp_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'text' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _certificateNumber_decorators, { kind: "field", name: "certificateNumber", static: false, private: false, access: { has: function (obj) { return "certificateNumber" in obj; }, get: function (obj) { return obj.certificateNumber; }, set: function (obj, value) { obj.certificateNumber = value; } }, metadata: _metadata }, _certificateNumber_initializers, _certificateNumber_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, null, _surname_decorators, { kind: "field", name: "surname", static: false, private: false, access: { has: function (obj) { return "surname" in obj; }, get: function (obj) { return obj.surname; }, set: function (obj, value) { obj.surname = value; } }, metadata: _metadata }, _surname_initializers, _surname_extraInitializers);
        __esDecorate(null, null, _firstName_decorators, { kind: "field", name: "firstName", static: false, private: false, access: { has: function (obj) { return "firstName" in obj; }, get: function (obj) { return obj.firstName; }, set: function (obj, value) { obj.firstName = value; } }, metadata: _metadata }, _firstName_initializers, _firstName_extraInitializers);
        __esDecorate(null, null, _otherNames_decorators, { kind: "field", name: "otherNames", static: false, private: false, access: { has: function (obj) { return "otherNames" in obj; }, get: function (obj) { return obj.otherNames; }, set: function (obj, value) { obj.otherNames = value; } }, metadata: _metadata }, _otherNames_initializers, _otherNames_extraInitializers);
        __esDecorate(null, null, _deceasedFirstName_decorators, { kind: "field", name: "deceasedFirstName", static: false, private: false, access: { has: function (obj) { return "deceasedFirstName" in obj; }, get: function (obj) { return obj.deceasedFirstName; }, set: function (obj, value) { obj.deceasedFirstName = value; } }, metadata: _metadata }, _deceasedFirstName_initializers, _deceasedFirstName_extraInitializers);
        __esDecorate(null, null, _deceasedLastName_decorators, { kind: "field", name: "deceasedLastName", static: false, private: false, access: { has: function (obj) { return "deceasedLastName" in obj; }, get: function (obj) { return obj.deceasedLastName; }, set: function (obj, value) { obj.deceasedLastName = value; } }, metadata: _metadata }, _deceasedLastName_initializers, _deceasedLastName_extraInitializers);
        __esDecorate(null, null, _idNumber_decorators, { kind: "field", name: "idNumber", static: false, private: false, access: { has: function (obj) { return "idNumber" in obj; }, get: function (obj) { return obj.idNumber; }, set: function (obj, value) { obj.idNumber = value; } }, metadata: _metadata }, _idNumber_initializers, _idNumber_extraInitializers);
        __esDecorate(null, null, _deceasedNationalId_decorators, { kind: "field", name: "deceasedNationalId", static: false, private: false, access: { has: function (obj) { return "deceasedNationalId" in obj; }, get: function (obj) { return obj.deceasedNationalId; }, set: function (obj, value) { obj.deceasedNationalId = value; } }, metadata: _metadata }, _deceasedNationalId_initializers, _deceasedNationalId_extraInitializers);
        __esDecorate(null, null, _nationality_decorators, { kind: "field", name: "nationality", static: false, private: false, access: { has: function (obj) { return "nationality" in obj; }, get: function (obj) { return obj.nationality; }, set: function (obj, value) { obj.nationality = value; } }, metadata: _metadata }, _nationality_initializers, _nationality_extraInitializers);
        __esDecorate(null, null, _gender_decorators, { kind: "field", name: "gender", static: false, private: false, access: { has: function (obj) { return "gender" in obj; }, get: function (obj) { return obj.gender; }, set: function (obj, value) { obj.gender = value; } }, metadata: _metadata }, _gender_initializers, _gender_extraInitializers);
        __esDecorate(null, null, _dateOfBirth_decorators, { kind: "field", name: "dateOfBirth", static: false, private: false, access: { has: function (obj) { return "dateOfBirth" in obj; }, get: function (obj) { return obj.dateOfBirth; }, set: function (obj, value) { obj.dateOfBirth = value; } }, metadata: _metadata }, _dateOfBirth_initializers, _dateOfBirth_extraInitializers);
        __esDecorate(null, null, _dateOfDeath_decorators, { kind: "field", name: "dateOfDeath", static: false, private: false, access: { has: function (obj) { return "dateOfDeath" in obj; }, get: function (obj) { return obj.dateOfDeath; }, set: function (obj, value) { obj.dateOfDeath = value; } }, metadata: _metadata }, _dateOfDeath_initializers, _dateOfDeath_extraInitializers);
        __esDecorate(null, null, _causeOfDeath_decorators, { kind: "field", name: "causeOfDeath", static: false, private: false, access: { has: function (obj) { return "causeOfDeath" in obj; }, get: function (obj) { return obj.causeOfDeath; }, set: function (obj, value) { obj.causeOfDeath = value; } }, metadata: _metadata }, _causeOfDeath_initializers, _causeOfDeath_extraInitializers);
        __esDecorate(null, null, _placeOfDeath_decorators, { kind: "field", name: "placeOfDeath", static: false, private: false, access: { has: function (obj) { return "placeOfDeath" in obj; }, get: function (obj) { return obj.placeOfDeath; }, set: function (obj, value) { obj.placeOfDeath = value; } }, metadata: _metadata }, _placeOfDeath_initializers, _placeOfDeath_extraInitializers);
        __esDecorate(null, null, _healthFacilityName_decorators, { kind: "field", name: "healthFacilityName", static: false, private: false, access: { has: function (obj) { return "healthFacilityName" in obj; }, get: function (obj) { return obj.healthFacilityName; }, set: function (obj, value) { obj.healthFacilityName = value; } }, metadata: _metadata }, _healthFacilityName_initializers, _healthFacilityName_extraInitializers);
        __esDecorate(null, null, _healthFacilityAddress_decorators, { kind: "field", name: "healthFacilityAddress", static: false, private: false, access: { has: function (obj) { return "healthFacilityAddress" in obj; }, get: function (obj) { return obj.healthFacilityAddress; }, set: function (obj, value) { obj.healthFacilityAddress = value; } }, metadata: _metadata }, _healthFacilityAddress_initializers, _healthFacilityAddress_extraInitializers);
        __esDecorate(null, null, _homeDistrict_decorators, { kind: "field", name: "homeDistrict", static: false, private: false, access: { has: function (obj) { return "homeDistrict" in obj; }, get: function (obj) { return obj.homeDistrict; }, set: function (obj, value) { obj.homeDistrict = value; } }, metadata: _metadata }, _homeDistrict_initializers, _homeDistrict_extraInitializers);
        __esDecorate(null, null, _homeTA_decorators, { kind: "field", name: "homeTA", static: false, private: false, access: { has: function (obj) { return "homeTA" in obj; }, get: function (obj) { return obj.homeTA; }, set: function (obj, value) { obj.homeTA = value; } }, metadata: _metadata }, _homeTA_initializers, _homeTA_extraInitializers);
        __esDecorate(null, null, _homeVillage_decorators, { kind: "field", name: "homeVillage", static: false, private: false, access: { has: function (obj) { return "homeVillage" in obj; }, get: function (obj) { return obj.homeVillage; }, set: function (obj, value) { obj.homeVillage = value; } }, metadata: _metadata }, _homeVillage_initializers, _homeVillage_extraInitializers);
        __esDecorate(null, null, _otherPlaceDetails_decorators, { kind: "field", name: "otherPlaceDetails", static: false, private: false, access: { has: function (obj) { return "otherPlaceDetails" in obj; }, get: function (obj) { return obj.otherPlaceDetails; }, set: function (obj, value) { obj.otherPlaceDetails = value; } }, metadata: _metadata }, _otherPlaceDetails_initializers, _otherPlaceDetails_extraInitializers);
        __esDecorate(null, null, _mannerOfDeath_decorators, { kind: "field", name: "mannerOfDeath", static: false, private: false, access: { has: function (obj) { return "mannerOfDeath" in obj; }, get: function (obj) { return obj.mannerOfDeath; }, set: function (obj, value) { obj.mannerOfDeath = value; } }, metadata: _metadata }, _mannerOfDeath_initializers, _mannerOfDeath_extraInitializers);
        __esDecorate(null, null, _accidentType_decorators, { kind: "field", name: "accidentType", static: false, private: false, access: { has: function (obj) { return "accidentType" in obj; }, get: function (obj) { return obj.accidentType; }, set: function (obj, value) { obj.accidentType = value; } }, metadata: _metadata }, _accidentType_initializers, _accidentType_extraInitializers);
        __esDecorate(null, null, _accidentDetails_decorators, { kind: "field", name: "accidentDetails", static: false, private: false, access: { has: function (obj) { return "accidentDetails" in obj; }, get: function (obj) { return obj.accidentDetails; }, set: function (obj, value) { obj.accidentDetails = value; } }, metadata: _metadata }, _accidentDetails_initializers, _accidentDetails_extraInitializers);
        __esDecorate(null, null, _residentialDistrict_decorators, { kind: "field", name: "residentialDistrict", static: false, private: false, access: { has: function (obj) { return "residentialDistrict" in obj; }, get: function (obj) { return obj.residentialDistrict; }, set: function (obj, value) { obj.residentialDistrict = value; } }, metadata: _metadata }, _residentialDistrict_initializers, _residentialDistrict_extraInitializers);
        __esDecorate(null, null, _residentialTA_decorators, { kind: "field", name: "residentialTA", static: false, private: false, access: { has: function (obj) { return "residentialTA" in obj; }, get: function (obj) { return obj.residentialTA; }, set: function (obj, value) { obj.residentialTA = value; } }, metadata: _metadata }, _residentialTA_initializers, _residentialTA_extraInitializers);
        __esDecorate(null, null, _residentialVillage_decorators, { kind: "field", name: "residentialVillage", static: false, private: false, access: { has: function (obj) { return "residentialVillage" in obj; }, get: function (obj) { return obj.residentialVillage; }, set: function (obj, value) { obj.residentialVillage = value; } }, metadata: _metadata }, _residentialVillage_initializers, _residentialVillage_extraInitializers);
        __esDecorate(null, null, _wasPregnant_decorators, { kind: "field", name: "wasPregnant", static: false, private: false, access: { has: function (obj) { return "wasPregnant" in obj; }, get: function (obj) { return obj.wasPregnant; }, set: function (obj, value) { obj.wasPregnant = value; } }, metadata: _metadata }, _wasPregnant_initializers, _wasPregnant_extraInitializers);
        __esDecorate(null, null, _pregnantAtDeath_decorators, { kind: "field", name: "pregnantAtDeath", static: false, private: false, access: { has: function (obj) { return "pregnantAtDeath" in obj; }, get: function (obj) { return obj.pregnantAtDeath; }, set: function (obj, value) { obj.pregnantAtDeath = value; } }, metadata: _metadata }, _pregnantAtDeath_initializers, _pregnantAtDeath_extraInitializers);
        __esDecorate(null, null, _motherSurname_decorators, { kind: "field", name: "motherSurname", static: false, private: false, access: { has: function (obj) { return "motherSurname" in obj; }, get: function (obj) { return obj.motherSurname; }, set: function (obj, value) { obj.motherSurname = value; } }, metadata: _metadata }, _motherSurname_initializers, _motherSurname_extraInitializers);
        __esDecorate(null, null, _motherFirstName_decorators, { kind: "field", name: "motherFirstName", static: false, private: false, access: { has: function (obj) { return "motherFirstName" in obj; }, get: function (obj) { return obj.motherFirstName; }, set: function (obj, value) { obj.motherFirstName = value; } }, metadata: _metadata }, _motherFirstName_initializers, _motherFirstName_extraInitializers);
        __esDecorate(null, null, _motherOtherNames_decorators, { kind: "field", name: "motherOtherNames", static: false, private: false, access: { has: function (obj) { return "motherOtherNames" in obj; }, get: function (obj) { return obj.motherOtherNames; }, set: function (obj, value) { obj.motherOtherNames = value; } }, metadata: _metadata }, _motherOtherNames_initializers, _motherOtherNames_extraInitializers);
        __esDecorate(null, null, _motherIdNo_decorators, { kind: "field", name: "motherIdNo", static: false, private: false, access: { has: function (obj) { return "motherIdNo" in obj; }, get: function (obj) { return obj.motherIdNo; }, set: function (obj, value) { obj.motherIdNo = value; } }, metadata: _metadata }, _motherIdNo_initializers, _motherIdNo_extraInitializers);
        __esDecorate(null, null, _motherNationality_decorators, { kind: "field", name: "motherNationality", static: false, private: false, access: { has: function (obj) { return "motherNationality" in obj; }, get: function (obj) { return obj.motherNationality; }, set: function (obj, value) { obj.motherNationality = value; } }, metadata: _metadata }, _motherNationality_initializers, _motherNationality_extraInitializers);
        __esDecorate(null, null, _fatherSurname_decorators, { kind: "field", name: "fatherSurname", static: false, private: false, access: { has: function (obj) { return "fatherSurname" in obj; }, get: function (obj) { return obj.fatherSurname; }, set: function (obj, value) { obj.fatherSurname = value; } }, metadata: _metadata }, _fatherSurname_initializers, _fatherSurname_extraInitializers);
        __esDecorate(null, null, _fatherFirstName_decorators, { kind: "field", name: "fatherFirstName", static: false, private: false, access: { has: function (obj) { return "fatherFirstName" in obj; }, get: function (obj) { return obj.fatherFirstName; }, set: function (obj, value) { obj.fatherFirstName = value; } }, metadata: _metadata }, _fatherFirstName_initializers, _fatherFirstName_extraInitializers);
        __esDecorate(null, null, _fatherOtherNames_decorators, { kind: "field", name: "fatherOtherNames", static: false, private: false, access: { has: function (obj) { return "fatherOtherNames" in obj; }, get: function (obj) { return obj.fatherOtherNames; }, set: function (obj, value) { obj.fatherOtherNames = value; } }, metadata: _metadata }, _fatherOtherNames_initializers, _fatherOtherNames_extraInitializers);
        __esDecorate(null, null, _fatherIdNo_decorators, { kind: "field", name: "fatherIdNo", static: false, private: false, access: { has: function (obj) { return "fatherIdNo" in obj; }, get: function (obj) { return obj.fatherIdNo; }, set: function (obj, value) { obj.fatherIdNo = value; } }, metadata: _metadata }, _fatherIdNo_initializers, _fatherIdNo_extraInitializers);
        __esDecorate(null, null, _fatherNationality_decorators, { kind: "field", name: "fatherNationality", static: false, private: false, access: { has: function (obj) { return "fatherNationality" in obj; }, get: function (obj) { return obj.fatherNationality; }, set: function (obj, value) { obj.fatherNationality = value; } }, metadata: _metadata }, _fatherNationality_initializers, _fatherNationality_extraInitializers);
        __esDecorate(null, null, _informantSurname_decorators, { kind: "field", name: "informantSurname", static: false, private: false, access: { has: function (obj) { return "informantSurname" in obj; }, get: function (obj) { return obj.informantSurname; }, set: function (obj, value) { obj.informantSurname = value; } }, metadata: _metadata }, _informantSurname_initializers, _informantSurname_extraInitializers);
        __esDecorate(null, null, _informantFirstName_decorators, { kind: "field", name: "informantFirstName", static: false, private: false, access: { has: function (obj) { return "informantFirstName" in obj; }, get: function (obj) { return obj.informantFirstName; }, set: function (obj, value) { obj.informantFirstName = value; } }, metadata: _metadata }, _informantFirstName_initializers, _informantFirstName_extraInitializers);
        __esDecorate(null, null, _informantOtherNames_decorators, { kind: "field", name: "informantOtherNames", static: false, private: false, access: { has: function (obj) { return "informantOtherNames" in obj; }, get: function (obj) { return obj.informantOtherNames; }, set: function (obj, value) { obj.informantOtherNames = value; } }, metadata: _metadata }, _informantOtherNames_initializers, _informantOtherNames_extraInitializers);
        __esDecorate(null, null, _informantIdNo_decorators, { kind: "field", name: "informantIdNo", static: false, private: false, access: { has: function (obj) { return "informantIdNo" in obj; }, get: function (obj) { return obj.informantIdNo; }, set: function (obj, value) { obj.informantIdNo = value; } }, metadata: _metadata }, _informantIdNo_initializers, _informantIdNo_extraInitializers);
        __esDecorate(null, null, _informantName_decorators, { kind: "field", name: "informantName", static: false, private: false, access: { has: function (obj) { return "informantName" in obj; }, get: function (obj) { return obj.informantName; }, set: function (obj, value) { obj.informantName = value; } }, metadata: _metadata }, _informantName_initializers, _informantName_extraInitializers);
        __esDecorate(null, null, _informantRelation_decorators, { kind: "field", name: "informantRelation", static: false, private: false, access: { has: function (obj) { return "informantRelation" in obj; }, get: function (obj) { return obj.informantRelation; }, set: function (obj, value) { obj.informantRelation = value; } }, metadata: _metadata }, _informantRelation_initializers, _informantRelation_extraInitializers);
        __esDecorate(null, null, _informantRelationship_decorators, { kind: "field", name: "informantRelationship", static: false, private: false, access: { has: function (obj) { return "informantRelationship" in obj; }, get: function (obj) { return obj.informantRelationship; }, set: function (obj, value) { obj.informantRelationship = value; } }, metadata: _metadata }, _informantRelationship_initializers, _informantRelationship_extraInitializers);
        __esDecorate(null, null, _informantAddress_decorators, { kind: "field", name: "informantAddress", static: false, private: false, access: { has: function (obj) { return "informantAddress" in obj; }, get: function (obj) { return obj.informantAddress; }, set: function (obj, value) { obj.informantAddress = value; } }, metadata: _metadata }, _informantAddress_initializers, _informantAddress_extraInitializers);
        __esDecorate(null, null, _informantPostalAddress_decorators, { kind: "field", name: "informantPostalAddress", static: false, private: false, access: { has: function (obj) { return "informantPostalAddress" in obj; }, get: function (obj) { return obj.informantPostalAddress; }, set: function (obj, value) { obj.informantPostalAddress = value; } }, metadata: _metadata }, _informantPostalAddress_initializers, _informantPostalAddress_extraInitializers);
        __esDecorate(null, null, _informantPhone_decorators, { kind: "field", name: "informantPhone", static: false, private: false, access: { has: function (obj) { return "informantPhone" in obj; }, get: function (obj) { return obj.informantPhone; }, set: function (obj, value) { obj.informantPhone = value; } }, metadata: _metadata }, _informantPhone_initializers, _informantPhone_extraInitializers);
        __esDecorate(null, null, _informantSignature_decorators, { kind: "field", name: "informantSignature", static: false, private: false, access: { has: function (obj) { return "informantSignature" in obj; }, get: function (obj) { return obj.informantSignature; }, set: function (obj, value) { obj.informantSignature = value; } }, metadata: _metadata }, _informantSignature_initializers, _informantSignature_extraInitializers);
        __esDecorate(null, null, _informantDate_decorators, { kind: "field", name: "informantDate", static: false, private: false, access: { has: function (obj) { return "informantDate" in obj; }, get: function (obj) { return obj.informantDate; }, set: function (obj, value) { obj.informantDate = value; } }, metadata: _metadata }, _informantDate_initializers, _informantDate_extraInitializers);
        __esDecorate(null, null, _villageHeadName_decorators, { kind: "field", name: "villageHeadName", static: false, private: false, access: { has: function (obj) { return "villageHeadName" in obj; }, get: function (obj) { return obj.villageHeadName; }, set: function (obj, value) { obj.villageHeadName = value; } }, metadata: _metadata }, _villageHeadName_initializers, _villageHeadName_extraInitializers);
        __esDecorate(null, null, _villageHeadIdNo_decorators, { kind: "field", name: "villageHeadIdNo", static: false, private: false, access: { has: function (obj) { return "villageHeadIdNo" in obj; }, get: function (obj) { return obj.villageHeadIdNo; }, set: function (obj, value) { obj.villageHeadIdNo = value; } }, metadata: _metadata }, _villageHeadIdNo_initializers, _villageHeadIdNo_extraInitializers);
        __esDecorate(null, null, _villageHeadSignature_decorators, { kind: "field", name: "villageHeadSignature", static: false, private: false, access: { has: function (obj) { return "villageHeadSignature" in obj; }, get: function (obj) { return obj.villageHeadSignature; }, set: function (obj, value) { obj.villageHeadSignature = value; } }, metadata: _metadata }, _villageHeadSignature_initializers, _villageHeadSignature_extraInitializers);
        __esDecorate(null, null, _villageHeadDate_decorators, { kind: "field", name: "villageHeadDate", static: false, private: false, access: { has: function (obj) { return "villageHeadDate" in obj; }, get: function (obj) { return obj.villageHeadDate; }, set: function (obj, value) { obj.villageHeadDate = value; } }, metadata: _metadata }, _villageHeadDate_initializers, _villageHeadDate_extraInitializers);
        __esDecorate(null, null, _villageHeadStamp_decorators, { kind: "field", name: "villageHeadStamp", static: false, private: false, access: { has: function (obj) { return "villageHeadStamp" in obj; }, get: function (obj) { return obj.villageHeadStamp; }, set: function (obj, value) { obj.villageHeadStamp = value; } }, metadata: _metadata }, _villageHeadStamp_initializers, _villageHeadStamp_extraInitializers);
        __esDecorate(null, null, _certificatePdfUrl_decorators, { kind: "field", name: "certificatePdfUrl", static: false, private: false, access: { has: function (obj) { return "certificatePdfUrl" in obj; }, get: function (obj) { return obj.certificatePdfUrl; }, set: function (obj, value) { obj.certificatePdfUrl = value; } }, metadata: _metadata }, _certificatePdfUrl_initializers, _certificatePdfUrl_extraInitializers);
        __esDecorate(null, null, _isValid_decorators, { kind: "field", name: "isValid", static: false, private: false, access: { has: function (obj) { return "isValid" in obj; }, get: function (obj) { return obj.isValid; }, set: function (obj, value) { obj.isValid = value; } }, metadata: _metadata }, _isValid_initializers, _isValid_extraInitializers);
        __esDecorate(null, null, _issuedAt_decorators, { kind: "field", name: "issuedAt", static: false, private: false, access: { has: function (obj) { return "issuedAt" in obj; }, get: function (obj) { return obj.issuedAt; }, set: function (obj, value) { obj.issuedAt = value; } }, metadata: _metadata }, _issuedAt_initializers, _issuedAt_extraInitializers);
        __esDecorate(null, null, _issuedBy_decorators, { kind: "field", name: "issuedBy", static: false, private: false, access: { has: function (obj) { return "issuedBy" in obj; }, get: function (obj) { return obj.issuedBy; }, set: function (obj, value) { obj.issuedBy = value; } }, metadata: _metadata }, _issuedBy_initializers, _issuedBy_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _districtRegistrarSignature_decorators, { kind: "field", name: "districtRegistrarSignature", static: false, private: false, access: { has: function (obj) { return "districtRegistrarSignature" in obj; }, get: function (obj) { return obj.districtRegistrarSignature; }, set: function (obj, value) { obj.districtRegistrarSignature = value; } }, metadata: _metadata }, _districtRegistrarSignature_initializers, _districtRegistrarSignature_extraInitializers);
        __esDecorate(null, null, _dateOfRegistration_decorators, { kind: "field", name: "dateOfRegistration", static: false, private: false, access: { has: function (obj) { return "dateOfRegistration" in obj; }, get: function (obj) { return obj.dateOfRegistration; }, set: function (obj, value) { obj.dateOfRegistration = value; } }, metadata: _metadata }, _dateOfRegistration_initializers, _dateOfRegistration_extraInitializers);
        __esDecorate(null, null, _deathEntryNumber_decorators, { kind: "field", name: "deathEntryNumber", static: false, private: false, access: { has: function (obj) { return "deathEntryNumber" in obj; }, get: function (obj) { return obj.deathEntryNumber; }, set: function (obj, value) { obj.deathEntryNumber = value; } }, metadata: _metadata }, _deathEntryNumber_initializers, _deathEntryNumber_extraInitializers);
        __esDecorate(null, null, _officialStamp_decorators, { kind: "field", name: "officialStamp", static: false, private: false, access: { has: function (obj) { return "officialStamp" in obj; }, get: function (obj) { return obj.officialStamp; }, set: function (obj, value) { obj.officialStamp = value; } }, metadata: _metadata }, _officialStamp_initializers, _officialStamp_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        DeathCertificate = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return DeathCertificate = _classThis;
}();
exports.DeathCertificate = DeathCertificate;
